#!/bin/sh

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to NocoDB's One-Click Droplet.

* Nocodb will be hosted at http://$myip:8080

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
